### ISSUE TITLE
missing script in xsl file

### ISSUE THREAD

**Issue by lbaumo** [astromatic/scamp#11]
I'm trying to display an xml file with Firefox, however, the tables no longer expand.  I get the following error: 

Loading failed for the <script> with source “http://terapix.iap.fr/cplt/xsl/sorttable.js”

If I visit terapix.iap.fr, here is the message i get: 

Thank you for your interest in content once hosted at terapix.iap.fr!
These pages have now been archived on a new server at calet.org.
They will no longer be updated.
If you can't find what you are looking for, please take a look at the archive layout.

is sorttable.js available somewhere else?

**Comment by lbaumo** [comment]
I found the file at "//astromatic.net/xsl/sorttable.js"

**Comment by ebertin** [comment]
Hi Lucie,
Sorry for not replying earlier. You must have run a very old version of SCAMP. `sorttable.js` is indeed now at [http://astromatic.net/xsl/sorttable.js](http://astromatic.net/xsl/sorttable.js).
Note however that the [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy) makes it very difficult to operate those XSL files nowadays. There is a branch of SCAMP developed by Sebastien Serre, with much improved diagnostics, that I still need to merge.
