### ISSUE TITLE
What replaced FGROUP_RADIUS

### ISSUE THREAD

**Issue by lbaumo** [astromatic/scamp#24]
Older versions of scamp had the parameter FGROUP_RADIUS in the config file, however this quantity has been removed from later versions.  Where can I set the field size now?

**Comment by ebertin** [comment]
It is not needed anymore! `FGROUP_RADIUS` was required by my original cross-matching algorithm, which was very basic. More recent versions of SCAMP rely on a much more efficient, [healpix](https://en.wikipedia.org/wiki/HEALPix)-based, cross-matching code (written by @ssbx), which automatically determines whether catalogs overlap or not.
