### ISSUE TITLE
SCAMP 2.7.2 seg fault on Mac when calculating colour shifts

### ISSUE THREAD

**Issue by mrkite92** [astromatic/scamp#6]
With ATLAS from fink, see attached crash report
[scamp_2018-08-23-162304_macprojb.crash.zip](https://github.com/astromatic/scamp/files/2314989/scamp_2018-08-23-162304_macprojb.crash.zip)

**Comment by mrkite92** [comment]
Found: line 149

xi = samp->msamp->colour;

should be

xi = samp->msamp ? samp->msamp->colour : 0.0;

**Comment by ebertin** [comment]
Yes that would do it but detections with samp->msamp at NULL are not reliable at all and their colors make no sense. I will have a look at it as soon as I find the time.

**Comment by mrkite92** [comment]
Hello Emmanuel,

> Yes that would do it but detections with samp->msamp at NULL are not reliable at all and their colors make no sense. I will have a look at it as soon as I find the time.
> 

C’est corrigé chez moi, j’ai ajouté un commentaire sur Github avec la correction (adaptée de la version du trunk AstrOmatic…), je viens d’en parler à Sébastien.



Cheers,
JB

**Comment by ebertin** [comment]
Fixed in 75c7ddd69dd52c17157ebcedb35fd4d2eefb399d.
